name = "openai-grok"
main = "worker.js"
compatibility_date = "2025-02-24"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "D1_DB"
database_name = "a1_db"
database_id = "3918354f-800f-4ead-b535-0b0a08a4cd9b"

[vars]
CONFIG_PASSWORD = "123"

[observability]
enabled = true
head_sampling_rate = 1 
